services:
  - type: web
    name: foto-word-clean
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-ita
      pip install -r requirements.txt
    startCommand: gunicorn app:app
